---
- name: 모든 노드에 공통 설정 적용
  hosts: all
  become: yes
  roles:
    - common  # roles/common 디렉토리의 역할을 실행


- name: 마스터 노드 설정
  hosts: master
  become: yes
  roles:
    - master  # roles/master 디렉토리의 역할을 실행


- name: 워커 노드 설정
  hosts: workers
  become: yes
  roles:
    - worker  # roles/worker 디렉토리의 역할을 실행


- name: 모든 노드가 Ready가 될 떄 까지 대기  
  hosts: master
  become: yes
  tasks:
    - name: Wait for nodes to be in Ready state
      shell: |
        /usr/bin/kubectl get nodes --no-headers | grep -c " Ready"
      register: ready_nodes
      retries: 15         # 최대 15회 시도
      delay: 20           # 20초 간격 (총 5분 대기)
      until: ready_nodes.stdout|int >= 3   # master(1) + worker(2)
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: false

    - debug:
        msg: "✅ {{ ready_nodes.stdout }} nodes are Ready! Proceeding with ArgoCD installation."

- name: 마스터 노드에 ArgoCD 및 MetalLB 설치
  hosts: master
  become: yes
  roles:
    - argocd
    - metallb

